# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fafd41a8c2f99e5eff5b0dc696e792d04b0df153b8b49f0e42a0dfa7695b2d22147ae1700ee59a37a1fd3e26b5347ff9e92056468233596a072452650f2123d

test:
  secret_key_base: 137fd75c589ed31a45079e4f83ea50d228e7b832cbd096a0f3770d5dc8b8d68e3537e284b87596a80751a1fd64268625f6231054a325cdaa6d0b24ce8a2962a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
